# Preparação dos Dados 🏗️ 🎲

<p style="text-align: right">Prof. Hélio Bomfim de Macêdo Filho</p>

## Sumário da Aula

<ul>
    <ul>
    <li>Reorganização 🗂️</li>
    <li>Transformação 🛠️</li>
</ul>

## Aspectos de Reorganização e Transformação dos Dados

<ul>
    <li>80% do tempo do cientista de dados é investido em carga; reorganização e transformação.
    <li>A maneira em que os dados estão armazenados em arquivos ou bancos de dados podem não corresponder ao formato apropriado para determinada tarefa;</li>
    <li>É comum o uso de linguagens de programação para transformar os dados de um formato para outro.</li>
        </ul>
    </li>
</ul>

### Biblioteca Principal 📚: pandas

<img src="https://pandas.pydata.org/docs/_static/pandas.svg" width="100" style="float: right;">

In [1]:
import pandas as pd

### Reorganização 🗂️ dos Dados 🎲

#### Seleção 🍕 e Filtro 🍝 em DataFrame 📽️

In [2]:
# Vamos analisar alguns dados de orgãos superiores do governo (em 2022)
# https://portaldatransparencia.gov.br/orgaos-superiores?ano=2022

ministerios = ['Educacao', 'Saude', 'Fazenda', 'Agricultura']
servidores = [374_209, 44_762, 50_820, 15_275]
folha_pagamento = [29_905, 4_015, 3_002, 2_741] # em R$ 1.000.000
valor_arrecadado = [34_622, 2_430, 3_434_537, 6_128] # em R$ 1.000.000
despesa = [139_593, 143_251, 2_308_118, 13_663] # em R$ 1.000.000

In [3]:
df = pd.DataFrame({
    'Servidores': servidores,
    'Folha de Pagamento': folha_pagamento,
    'Valor Arrecadado': valor_arrecadado,
    'Despesa': despesa
}, index = ministerios)

In [4]:
df

             Servidores  Folha de Pagamento  Valor Arrecadado  Despesa
Educacao         374209               29905             34622   139593
Saude             44762                4015              2430   143251
Fazenda           50820                3002           3434537  2308118
Agricultura       15275                2741              6128    13663

<pre> Você pode <b>selecionar</b> uma coluna de um DataFrame pelo nome da coluna -- e retornar Serie</pre>

In [5]:
df['Folha de Pagamento']

Educacao       29905
Saude           4015
Fazenda         3002
Agricultura     2741
Name: Folha de Pagamento, dtype: int64

<pre>Você pode <b>selecionar</b> colunas de um DataFrame pela lista dos nomes das colunas -- e retornar DataFrame</pre>

In [6]:
df[['Valor Arrecadado', 'Servidores']]

             Valor Arrecadado  Servidores
Educacao                34622      374209
Saude                    2430       44762
Fazenda               3434537       50820
Agricultura              6128       15275

<pre>Você pode <b>filtrar</b> linhas de um DataFrame com slicing -- e retornar DataFrame</pre>

In [7]:
df[:2]

          Servidores  Folha de Pagamento  Valor Arrecadado  Despesa
Educacao      374209               29905             34622   139593
Saude          44762                4015              2430   143251

<pre>Você pode combinar <b>seleção</b> e <b>filtro</b> de um DataFrame com <i>boolean indexing</i> -- e retornar DataFrame</pre>

In [8]:
df[df['Servidores'] > 50000]

          Servidores  Folha de Pagamento  Valor Arrecadado  Despesa
Educacao      374209               29905             34622   139593
Fazenda        50820                3002           3434537  2308118

<pre>🍒 🎂 Você pode inclusive atribuir um valor às células <b>filtradas</b> pela operação imediatamente acima</pre>

In [9]:
df[df['Servidores'] > 50000] = 0
df

             Servidores  Folha de Pagamento  Valor Arrecadado  Despesa
Educacao              0                   0                 0        0
Saude             44762                4015              2430   143251
Fazenda               0                   0                 0        0
Agricultura       15275                2741              6128    13663

👉 dica: dependendo do tipo de dados do índice do DataFrame, utilizar inteiro entre colchetes <b>[ ]</b> pode ser confuso. <br />O inteiro se refere ao valor do índice ou à posição da sequência no índice? na dúvida, tenha preferência por usar as funções:
    <ul>
        <li><b>loc</b>: usa o valor do índice como elemento de filtro; e</li>
        <li><b>iloc</b>: usa a posição da sequência no índice como elemento de filtro.</li>
    </ul>

<pre>Com loc, você pode ... </pre>

<pre>... <b>filtrar</b> uma linha de um DataFrame pelo nome da linha -- e retornar Serie...</pre>

In [10]:
df.loc['Saude']

Servidores             44762
Folha de Pagamento      4015
Valor Arrecadado        2430
Despesa               143251
Name: Saude, dtype: int64

<pre>... <b>filtrar</b> linhas de um DataFrame pela lista dos nomes das linhas -- e retornar DataFrame...</pre>

In [11]:
df.loc[["Saude", "Agricultura"]]

             Servidores  Folha de Pagamento  Valor Arrecadado  Despesa
Saude             44762                4015              2430   143251
Agricultura       15275                2741              6128    13663

<pre>... combinar <b>seleção</b> e <b>filtro</b> de um DataFrame -- com vírgula separando linhas de colunas...</pre>

In [12]:
df.loc["Saude", ["Folha de Pagamento", "Valor Arrecadado"]]

Folha de Pagamento    4015
Valor Arrecadado      2430
Name: Saude, dtype: int64

<pre>Igualmente, com <i>iloc</i>, você pode repetir a sequência de operações imediatamente acima</pre>

In [13]:
df.iloc[1]

Servidores             44762
Folha de Pagamento      4015
Valor Arrecadado        2430
Despesa               143251
Name: Saude, dtype: int64

In [14]:
df.iloc[[1, 3]]

             Servidores  Folha de Pagamento  Valor Arrecadado  Despesa
Saude             44762                4015              2430   143251
Agricultura       15275                2741              6128    13663

In [15]:
df.iloc[3, [3, 0, 1]]

Despesa               13663
Servidores            15275
Folha de Pagamento     2741
Name: Agricultura, dtype: int64

In [16]:
df.iloc[[1, 2], [3, 0, 1]]

         Despesa  Servidores  Folha de Pagamento
Saude     143251       44762                4015
Fazenda        0           0                   0

##### Quadro-resumo dos métodos de Seleção 🍕 e Filtro 🍝 em DataFrame 📽️

<table>
    <tr><th>Opção</th><th>Descrição</th></tr>
    <tr><td>df[column]</td><td>Selecione uma única coluna ou sequência de colunas do DataFrame; <br />Os casos especiais: <ol><li>Vetor booleano: filtra linhas;</li><li>Slice: fatia linhas; e</li><li>DataFrame booleano: atribui valores com base em critérios.</li></ol></td></tr>
    <tr><td>df.loc[rows]</td><td>Selecione uma única linha ou subconjunto de linhas do DataFrame pelos rótulos do índices</td></tr>
    <tr><td>df.loc[:, cols]</td><td>Selecione uma única coluna ou subconjunto de colunas pelos rótulo dos índices</td></tr>
    <tr><td>df.loc[rows, cols]</td><td>Selecione linha(s) e coluna(s) pelos rótulos do índices</td></tr>
    <tr><td>df.iloc[rows]</td><td>Selecione uma única linha ou subconjunto de linhas do DataFrame pela posição na sequência do índice</td></tr>
    <tr><td>df.iloc[:, cols]</td><td>Selecione uma única coluna ou subconjunto de colunas pela posições nas sequências dos índices</td></tr>
    <tr><td>df.iloc[rows, cols]</td><td>Selecione tanto linha(s) quanto coluna(s) pela posições nas sequências dos índices</td></tr>
    <tr><td>df.at[row, col]</td><td>Selecione um único valor escalar pelos rótulos do índices</td></tr>
    <tr><td>df.iat[row, col]</td><td>Selecione um único valor escalar pela posições nas sequências dos índices</td></tr>
    <tr><td>reindex method</td><td>Selecione linhas ou colunas pelos rótulos do índices</td></tr>
</table>

### Transformação 🛠️ dos Dados 🎲

<pre>Operações importantes de preparação.</pre>

#### Transformando Dados com Mapeamento (De/Para)

<pre>Por alguma razão, você pode precisar mapear valores de um vetor, Series ou coluna de um DataFrame</pre>

In [17]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], 
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [18]:
data[['k1']]

    k1
0  one
1  two
2  one
3  two
4  one
5  two
6  two

<pre>Você pode fazer isso com o uso de um dicionário...</pre>

In [19]:
en_to_pt = {'one': 'um', 'two': 'dois'}
data['k1'].map(en_to_pt)

0      um
1    dois
2      um
3    dois
4      um
5    dois
6    dois
Name: k1, dtype: str

<pre>... ou de uma função.</pre>

In [20]:
data['k1'].map(lambda x: 'um' if x == 'one' else 'dois')

0      um
1    dois
2      um
3    dois
4      um
5    dois
6    dois
Name: k1, dtype: str

In [21]:
data['k1'].map(str.capitalize)

0    One
1    Two
2    One
3    Two
4    One
5    Two
6    Two
Name: k1, dtype: str

#### Substituindo Valores

<pre>Por alguma razão, você pode precisar substituir valores do DataFrame (operação mais ampla que o <i>map</i>)</pre>

<pre>Você pode fazer isso com o uso de um dicionário...</pre>

In [22]:
data.replace(en_to_pt)

     k1  k2
0    um   1
1  dois   1
2    um   2
3  dois   3
4    um   3
5  dois   4
6  dois   4

<pre>... ou de duas listas de valores: uma com valores a serem substituídos e outra com seus respectivos substitutos.</pre>

In [23]:
data.replace(['one', 'two'], ['um', 'dois'])

     k1  k2
0    um   1
1  dois   1
2    um   2
3  dois   3
4    um   3
5  dois   4
6  dois   4

#### Discretizando e Compartimentalizando (<i>Bin</i>)

<pre>Dados contínuos com frequência são discretizados ou, alternativamente, separados em compartimentos</pre>

In [24]:
idades = pd.DataFrame({'idade': [20, 22, 25, 27, 1, 23,
                                 37, 31, 61, 45, 41, 32]})
idades

    idade
0      20
1      22
2      25
3      27
4       1
5      23
6      37
7      31
8      61
9      45
10     41
11     32

In [25]:
idades['faixa_etaria'] = pd.cut(idades['idade'], [18, 25, 35, 60, 100])
idades

    idade   faixa_etaria
0      20   (18.0, 25.0]
1      22   (18.0, 25.0]
2      25   (18.0, 25.0]
3      27   (25.0, 35.0]
4       1            NaN
5      23   (18.0, 25.0]
6      37   (35.0, 60.0]
7      31   (25.0, 35.0]
8      61  (60.0, 100.0]
9      45   (35.0, 60.0]
10     41   (35.0, 60.0]
11     32   (25.0, 35.0]

<font size=7><center><code>Executem todo este caderno...</code></center></font>