In [1]:
!pip install --upgrade lxml --quiet
!pip install --upgrade pandas --quiet

In [2]:
import json
import requests

In [3]:
import os
os.makedirs('data/output', exist_ok=True)

# Fontes de Dados 🚰 🎲<br />(e seus Tipos de Arquivos)

[![Abrir no Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/heliomacedofilho/idp_nivelamento_2026/blob/main/Parte%2001/Fontes%20de%20Dados.ipynb)

<p style="text-align: right">Prof. Hélio Bomfim de Macêdo Filho</p>

## Sumário da Aula

<ul>
    <li>Aspectos de Fontes de Dados 🚰 🎲</li>
    <li>Arquivos de compartilhamento de dados 🗂️
        <ul>
            <li>CSV;</li>
            <li>JSON;</li>
            <li>XML.</li>
        </ul>
    </li>
    <li>Planilhas 🧾.</li>
</ul>

## Aspectos de Fontes de Dados ⛲️🎲

Acessar dados é o primeiro passo necessário para usar a maior parte das ferramentas deste Mestrado.

Há várias ferramentas em bibliotecas para ajudar na leitura e na escrita de dados em diversos formatos.

A entrada e a saída de dados geralmente se enquadram nas principais categorias a seguir:

<ul>
    <li>Leitura de arquivos-texto e outros formatos mais eficientes em disco;
        <ul><li>(assunto desse caderno)</li></ul>
    </li>
    <li>Interação com fontes de dados da Internet.</li>
    </ul>
</ul>

### Arquivos de compartilhamento de dados 🗂️

<pre>Pelo navegador, vamos acessar dados de georreferenciamento de estados e municípios brasileiros em formato <b>CSV</b> e em formato <b>JSON</b>.</pre>

👉 dados de georreferenciamento dos estados brasileiros em <a href='https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/estados.csv'>CSV</a> e em <a href="https://raw.githubusercontent.com/kelvins/municipios-brasileiros/refs/heads/main/json/estados.json">JSON</a>.

👉 dados de georreferenciamento dos municípios brasileiros em <a href='https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv'>CSV</a> e em <a href="https://raw.githubusercontent.com/kelvins/municipios-brasileiros/refs/heads/main/json/municipios.json">JSON</a>.

#### CSV

Valores separados por vírgula (CSV, do inglês Comma-separated values) é um formato de arquivo de texto que usa
- vírgulas para separar valores; e 
- quebras de linha para separar registros.

Um arquivo CSV armazena dados tabulares (números e texto) em texto simples, onde cada linha do arquivo normalmente representa um registro de dados.

Cada registro consiste no mesmo número de campos, e estes são separados por vírgulas no arquivo CSV.

🚨 Se o próprio delimitador de campo puder aparecer dentro de um campo, os campos podem ser cercados por aspas. 🚨

👉 Saiba mais sobre arquivos <a href='https://en.wikipedia.org/wiki/Comma-separated_values'>CSV</a>

<pre>Vamos ler as linhas de um arquivo CSV.</pre>

In [4]:
with open('data/estados.csv') as estados_csv:
    for linha in estados_csv.readlines()[:5]:
        print(linha, end='')

codigo_uf,uf,nome,latitude,longitude,regiao
11,RO,Rondônia,-10.83,-63.34,Norte
12,AC,Acre,-8.77,-70.55,Norte
13,AM,Amazonas,-3.47,-65.1,Norte
14,RR,Roraima,1.99,-61.33,Norte

<pre>🚨 pandas é simples e amigável para ler csv</pre>

In [5]:
from pandas import read_csv

df = read_csv('data/estados.csv')
df.head()

   codigo_uf  uf      nome  latitude  longitude regiao
0         11  RO  Rondônia    -10.83     -63.34  Norte
1         12  AC      Acre     -8.77     -70.55  Norte
2         13  AM  Amazonas     -3.47     -65.10  Norte
3         14  RR   Roraima      1.99     -61.33  Norte
4         15  PA      Pará     -3.79     -52.48  Norte

<pre>🚨 igualmente simples e amigável para escrever csv</pre>

In [6]:
df.to_csv('data/output/estados_aux.csv', index=False)

#### JSON

Um formato que contém dois tipos de dados:
- Tipos de Dados Primitidos: Números, Cadeias de Caracteres, Booleanos, Nulo.
- Estruturas de Dados: Vetor, Objeto.

👉 Saiba mais sobre arquivos <a href='https://en.wikipedia.org/wiki/JSON'>JSON</a>

Os tipos de dados primitivos são representados como:
- Número: um número decimal (com sinal), que pode conter uma parte fracionária e pode usar a notação exponencial $e$.
    - <i>e.g.</i>, +10.59
- Cadeia de Caracteres: uma sequência de zero ou mais caracteres <a href="https://en.wikipedia.org/wiki/Unicode">unicode</a>, entre aspas duplas.
    - <i>e.g.</i>, "cadeia de caracteres"
- Booleano: ou verdadeiro (<b>true</b>) ou falso (<b>false</b>).
- Nulo: um valor vazio, codificado como <b>null</b>.

As estruturas de dados são representadas como:
- Vetor: uma lista ordenada de zero ou mais elementos, cada um sendo de qualquer tipo de dados.
    - <i>e.g.</i>, [elem1, elem2, elem3]
- Objeto: uma coleção de pares nome-valor, onde os nomes são cadeias de caracteres.
    - <i>e.g.</i>, {"chave1": elem1, "chave2": elem2, "chave3": elem3}

<pre>Vamos ler as linhas de um arquivo JSON.</pre>

In [7]:
with open('data/estados.json') as estados_json:
    estados_json = json.load(estados_json)
    estados_dump = json.dumps(estados_json, indent=2)
    print(estados_dump[:285], end='')

[
  {
    "codigo_uf": 11,
    "uf": "RO",
    "nome": "Rond\u00f4nia",
    "latitude": -10.83,
    "longitude": -63.34,
    "regiao": "Norte"
  },
  {
    "codigo_uf": 12,
    "uf": "AC",
    "nome": "Acre",
    "latitude": -8.77,
    "longitude": -70.55,
    "regiao": "Norte"
  },

<pre>🚨 pandas é simples e amigável para ler json</pre>

In [8]:
from pandas import read_json

df = read_json('data/estados.json')
df.head()

   codigo_uf  uf      nome  latitude  longitude regiao
0         11  RO  Rondônia    -10.83     -63.34  Norte
1         12  AC      Acre     -8.77     -70.55  Norte
2         13  AM  Amazonas     -3.47     -65.10  Norte
3         14  RR   Roraima      1.99     -61.33  Norte
4         15  PA      Pará     -3.79     -52.48  Norte

<pre>🚨 igualmente é simples e amigável para escrever json</pre>

In [9]:
df.to_json('data/output/estados_aux.json', index=False)

#### XML

"Extensible Markup Language (XML) is a markup language and file format for storing, transmitting, and reconstructing arbitrary data."

Formato vem caindo em desuso. Vamos comentar o formato com nosso exemplo concreto.

👉 Saiba mais sobre arquivos <a href='https://en.wikipedia.org/wiki/XML'>XML</a>

<pre>Vamos ler as linhas de um arquivo XML.</pre>

In [10]:
with open('data/estados.xml') as estados_xml:
    estados_xml_str = ''.join(estados_xml.readlines())
    print(estados_xml_str[:530])

<?xml version='1.0' encoding='utf-8'?>
<data>
  <row>
    <codigo_uf>11</codigo_uf>
    <uf>RO</uf>
    <nome>Rondônia</nome>
    <latitude>-10.83</latitude>
    <longitude>-63.34</longitude>
    <regiao>Norte</regiao>
  </row>
  <row>
    <codigo_uf>12</codigo_uf>
    <uf>AC</uf>
    <nome>Acre</nome>
    <latitude>-8.77</latitude>
    <longitude>-70.55</longitude>
    <regiao>Norte</regiao>
  </row>
  <row>
    <codigo_uf>13</codigo_uf>
    <uf>AM</uf>
    <nome>Amazonas</nome>
    <latitude>-3.47</latitude>
    <longitude

<pre>🚨 pandas é simples e amigável para ler xml</pre>

In [11]:
from pandas import read_xml

df = read_xml('data/estados.xml')
df.head()

   codigo_uf  uf      nome  latitude  longitude regiao
0         11  RO  Rondônia    -10.83     -63.34  Norte
1         12  AC      Acre     -8.77     -70.55  Norte
2         13  AM  Amazonas     -3.47     -65.10  Norte
3         14  RR   Roraima      1.99     -61.33  Norte
4         15  PA      Pará     -3.79     -52.48  Norte

<pre>🚨 igualmente é simples e amigável para escrever xml</pre>

In [12]:
df.to_xml('data/output/estados_aux.xml')

### Planilhas 🧾

"Office Open XML is a zipped, XML-based file format developed by Microsoft for representing spreadsheets [...]"

Principal formato nas organizações, Administração Pública ou Instituição Privada.

👉 Saiba mais sobre arquivos <a href='https://en.wikipedia.org/wiki/Office_Open_XML'>XLSX</a>

#### Biblioteca(s) Principal(is) 📚: <a href='https://pypi.org/project/openpyxl/'>openpyxl</a>

Antes de seguirmos, precisamos instalar a biblioteca ```openpyxl``` para que o pandas consiga realizar a leitura e escrita de planilhas.

In [13]:
!pip install --upgrade openpyxl --quiet

<pre>🚨 pandas é simples e amigável para ler planilha Excel</pre>

In [14]:
from pandas import read_excel

df_estados = read_excel('data/georreferenciamento.xlsx', 
                        sheet_name='Estados')
df_estados.head()

   codigo_uf  uf      nome  latitude  longitude regiao
0         11  RO  Rondônia    -10.83     -63.34  Norte
1         12  AC      Acre     -8.77     -70.55  Norte
2         13  AM  Amazonas     -3.47     -65.10  Norte
3         14  RR   Roraima      1.99     -61.33  Norte
4         15  PA      Pará     -3.79     -52.48  Norte

In [15]:
from pandas import read_excel

df_municipios = read_excel('data/georreferenciamento.xlsx', 
                           sheet_name='Municípios')
df_municipios.head()

        id state                     city
0  1100015    RO   Alta Floresta D''Oeste
1  1100379    RO  Alto Alegre dos Parecis
2  1100403    RO             Alto Paraíso
3  1100346    RO        Alvorada D''Oeste
4  1100023    RO                Ariquemes

<pre>🚨 igualmente é simples e amigável para escrever planilhas</pre>

In [16]:
df_estados.to_excel('data/output/estados_aux.xlsx', index=False)

👉 Caso deseje escrever em abas, precisamos recorrer ao `ExcelWriter`

In [17]:
from pandas import ExcelWriter

with ExcelWriter('data/output/georreferenciamento_aux.xlsx') as writer:
    df_estados.to_excel(writer, sheet_name='Estados', 
                        index=False)
    df_municipios.to_excel(writer, sheet_name='Municípios', 
                           index=False)

<font size=7><center><code>Executem todo este caderno...</code></center></font>