# Tratamento dos Dados 🪢

<p style="text-align: right">Prof. Hélio Bomfim de Macêdo Filho</p>

## Sumário da Aula

<ul>
    <li>Aspectos de Tratamento dos Dados 🪢</li>
    <li>Junção, Mescla e Concatenação 🥇</li>
    <li>Pivoteamento 🥈</li>
</ul>

### Biblioteca Principal 📚: pandas

<img src="https://pandas.pydata.org/docs/_static/pandas.svg" width="100" style="float: right;">

In [1]:
import pandas as pd

## Junção, Mescla e Concatenação 🥇

Os dados de objetos pandas podem ser combinados conforme as operações a seguir.

<table>
    <tr><th>Opção</th><th>Descrição</th></tr>
    <tr><td>pandas.merge</td><td>Conecta linhas em DataFrames com base em uma ou mais chaves. Essa operação será conhecida dos usuários de SQL ou de outros bancos de dados relacionais, pois ela implementa as operações de junção (join) dos bancos de dados</td></tr>
    <tr><td>pandas.concat</td><td>Concatena ou "empilha" objetos ao longo de um eixo</td></tr>
</table>

### Junção

In [2]:
infectados = pd.DataFrame([['ce', 'fortaleza', 10, 1], \
                           ['rj', 'rio de janeiro', 20, 2], \
                           ['df', 'brasília', 30, 3]], \
                          columns=['estado', 'municipio', 
                                   'casos', 'óbitos'])

vacinados = pd.DataFrame([['ce', 'fortaleza', 100], \
                          ['rj', 'rio de janeiro', 200], \
                          ['rn', 'natal', 300]], \
                         columns=['estado', 'municipio', 
                                  'habitantes vacinados'])

#### Inner Join

<pre>Inner join utiliza somente as combinacões de chaves observadas nas duas tabelas sendo combinadas</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Inner Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [3]:
pd.merge(infectados, vacinados, how='inner')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                   100
1     rj  rio de janeiro     20       2                   200

#### Left Outer Join

<pre>Left Outer Join utiliza todas as combinacões de chaves encontradas na tabela à esquerda</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Left Outer Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                  <td bgcolor='gray'>NaN</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [4]:
pd.merge(infectados, vacinados, how='left')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                 100.0
1     rj  rio de janeiro     20       2                 200.0
2     df        brasília     30       3                   NaN

#### Right Outer Join

<pre>Right Outer Join utiliza todas as combinacões de chaves encontradas na tabela à direita</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Left Outer Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10.0</td>
                  <td bgcolor='yellow'>1.0</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [5]:
pd.merge(infectados, vacinados, how='right')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza   10.0     1.0                   100
1     rj  rio de janeiro   20.0     2.0                   200
2     rn           natal    NaN     NaN                   300

#### Outer Join

<pre>Outer Join utiliza todas as combinacões de chaves observadas nas duas tabelas em conjunto</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Outer Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasilia</td>
                  <td bgcolor='gray'>30.0</td>
                  <td bgcolor='gray'>3.0</td>
                  <td bgcolor='gray'>NaN</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [6]:
pd.merge(infectados, vacinados, how='outer')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza   10.0     1.0                 100.0
1     df        brasília   30.0     3.0                   NaN
2     rj  rio de janeiro   20.0     2.0                 200.0
3     rn           natal    NaN     NaN                 300.0

#### Quadro-resumo das opções de junção

<table>
    <tr><th>Opção</th><th>Comportamento</th></tr>
    <tr><td>how='inner'</td><td>Utiliza somente as combinacões de chaves observadas nas duas tabelas sendo combinadas</td></tr>
    <tr><td>how='left'</td><td>Utiliza todas as combinacões de chaves encontradas na tabela à esquerda</td></tr>
    <tr><td>how='right'</td><td>Utiliza todas as combinacões de chaves encontradas na tabela à direita</td></tr>
    <tr><td>how='outer'</td><td>Utiliza todas as combinacões de chaves observadas nas duas tabelas em conjunto</td></tr>
</table>

<img src='figs/outer-join.gif' width='600px' style='margin-left: auto; margin-right: auto;'>

👉 dica: a(s) chave(s) pode(m) ser inferida(s) a partir do contexto da interseção entre as tabelas, mas também pode(m) ser especificada(s) com o parâmetro <i>on</i>

### Mescla

In [7]:
pd.merge(infectados, vacinados, 
         on=['estado', 'municipio'], how='inner')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                   100
1     rj  rio de janeiro     20       2                   200

👉 mais dica: caso a(s) chave(s) não possa(m) ser inferida(s), com nomes diferentes de coluna, deve-se especificá-la(s) com os parâmetros <i>left_on</i> e <i>right_on</i>

In [8]:
pd.merge(infectados, vacinados, left_on=['estado', 'municipio'], 
         right_on=['estado', 'municipio'],  how='inner')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                   100
1     rj  rio de janeiro     20       2                   200

<pre>🍒 🎂 Você pode também combinar duas tabelas com a operação de junção na presença de índice hierárquico (<i>join</i>)</pre>

In [9]:
infectados = infectados.set_index(['estado', 'municipio'])
infectados

                       casos  óbitos
estado municipio
ce     fortaleza          10       1
rj     rio de janeiro     20       2
df     brasília           30       3

In [10]:
vacinados = vacinados.set_index(['estado', 'municipio'])
vacinados

                       habitantes vacinados
estado municipio
ce     fortaleza                        100
rj     rio de janeiro                   200
rn     natal                            300

In [11]:
infectados.join(vacinados, how='inner')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza          10       1                   100
rj     rio de janeiro     20       2                   200

In [12]:
infectados.join(vacinados, how='left')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza          10       1                 100.0
rj     rio de janeiro     20       2                 200.0
df     brasília           30       3                   NaN

In [13]:
infectados.join(vacinados, how='right')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                   100
rj     rio de janeiro   20.0     2.0                   200
rn     natal             NaN     NaN                   300

In [14]:
infectados.join(vacinados, how='outer')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                 100.0
df     brasília         30.0     3.0                   NaN
rj     rio de janeiro   20.0     2.0                 200.0
rn     natal             NaN     NaN                 300.0

### Concatenação

<pre>Você pode empilhar ao longo das linhas com uma tabela em cima da outra (alinhando os índices das colunas)...</pre>

<table>
    <tr><th>Tabelas Acima e Abaixo</th><th>Tabelas Concatenadas</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
            <br />
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10.0</td>
                  <td bgcolor='yellow'>1.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasilia</td>
                  <td bgcolor='gray'>30.0</td>
                  <td bgcolor='gray'>3.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td>NaN</td>
                  <td>NaN</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>4</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td>NaN</td>
                  <td>NaN</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>5</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td>NaN</td>
                  <td>NaN</td>
                  <td bgcolor='pink'>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [15]:
pd.concat([infectados, vacinados], axis='index')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                   NaN
rj     rio de janeiro   20.0     2.0                   NaN
df     brasília         30.0     3.0                   NaN
ce     fortaleza         NaN     NaN                 100.0
rj     rio de janeiro    NaN     NaN                 200.0
rn     natal             NaN     NaN                 300.0

<pre>... bem como pode ao longo das colunas com uma tabela após a outra (alinhando os índices das linhas)...</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Tabelas Concatenadas</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10.0</td>
                  <td bgcolor='yellow'>1.0</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasilia</td>
                  <td bgcolor='gray'>30.0</td>
                  <td bgcolor='gray'>3.0</td>
                  <td bgcolor='gray'>NaN</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [16]:
pd.concat([infectados, vacinados], axis='columns')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                 100.0
rj     rio de janeiro   20.0     2.0                 200.0
df     brasília         30.0     3.0                   NaN
rn     natal             NaN     NaN                 300.0

<font size=7><center><code>Executem todo este caderno...</code></center></font>